---
- hosts: all
  vars:
    my_message: 'CloudForms was here'
  tasks:
    - name: Create a file...
      copy: dest=~/cloudforms.txt content="{{ my_message }}"
    - name: Create another file...
      copy: dest=/root/cloudforms.txt content="{{ my_message }}"