---
- hosts: all

  roles:
    - php
    - nginx

  environment:
    http_proxy: http://62.81.0.143:80
    https_proxy: http://62.81.0.143:80
  
  tasks:
  - name: Subscribe 
    command: subscription-manager register --username iveronar1@redhat.com --password f7C-Zqk-ctH-SCG
    
  - name: Attach pool 
    #command: subscription-manager attach --pool=8a85f98144844aff014488d059f61625
    command: subscription-manager attach 
  
  - name: Disable repos 
    command: subscription-manager repos --disable=*

  - name: Enable repos 
    command: subscription-manager repos --enable=rhel-7-server-optional-rpms --enable=rhel-7-server-extras-rpms --enable=rhel-7-server-rh-common-rpms --enable=rhel-7-server-rpms 
  
  - name: install the EPEL repo
    yum:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      state: present

  - name: "Install Nagios NRPE"
    yum: state=present name={{ item }}
    with_items:
    - nrpe

  - name: Push NRPE configuration
    copy:
      src: config_files/nrpe.cfg
      dest: /etc/nagios/nrpe.cfg
      owner: root
      group: root
      mode: 0644

  - name: Create bin folder
    file:
      path: /opt/nagios/bin/
      state: directory
      mode: 0755

  - name: Push NRPE check scripts
    unarchive:
      src: bin/nagios_checks.tar
      dest: /opt/nagios/bin/

  - name: enable service NRPE
    systemd:
      name: nrpe
      state: started 
      enabled: yes

  - name: Install ntp
    yum:
      name: ntp
      state: present

  - name: Disable chronyd
    systemd:
      name: chronyd
      state: stopped 
      enabled: no

  - name: enable service ntpd
    systemd:
      name: ntpd
      state: started 
      enabled: yes

  - name: Push NTP configuration
    copy:
      src: config_files/ntp.conf
      dest: /etc/ntp.conf
        
